services:
  trackingIP_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: trackingIPDB
      POSTGRES_USER: trackingIpUser
      POSTGRES_PASSWORD: trackingIpUser0001
    ports:
      - "30001:5432"
    networks:
      - geoipservice-network

  geoipservice_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - trackingIP_postgres
    ports:
      - "8081:8081"
    networks:
      - geoipservice-network

networks:
  geoipservice-network:
    driver: bridge